# Generated by Django 3.2.7 on 2022-12-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_questionscategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionscategory',
            options={'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='quizcategory',
            options={'verbose_name_plural': 'Категории тестов'},
        ),
        migrations.AlterField(
            model_name='quizcategory',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
